name = "kpakpando-airtime-tracker-api"
main = "./worker.ts"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "kpakpando-airtime-tracker"
database_id = "e531422a-fcbe-4c9a-8a4f-162b57d03086"
migrations_dir = "migrations"

[vars]
ALLOWED_ORIGINS = "https://kpakpando-airtime-tracker.vercel.app"
VAPID_SUBJECT = "mailto:kpakpandofm@gmail.com"

[triggers]
crons = ["* * * * *"]